name 'krishna-assignment'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures krishna-assignment'
long_description 'Installs/Configures krishna-assignment'
version '0.1.0'
