default['nginx']['server_name'] = "krishna.example.com"
default['nginx']['server_crt'] = "krishna.example.com.crt"
default['nginx']['server_key'] = "krishna.example.com.key"
default['nginx']['server_ca_crt'] = "krishna.example.com.ca.crt"
default['nginx']['lb_hostname'] = "192.168.33.11"
